### PR TITLE
Documentation & Debug Configuration Updates

### PR DESCRIPTION
**Pull request by JanBaig**
Hello, 
Made the following changes 
- Turns out that `getStdOut` only works from within a function on Windows and was the cause of the error we've briefly discussed previously. I've shifted it to be inside the `main` function
- Added some debug configurations needed to debug Zig on vscode (text editor I'm using)
- Fixed the path on the `Hacking.md` file

I'm not sure which IDE you use, so am unsure of how useful the addition of the vscode configurations is to the main repo. 
Additionally - I've noticed that the introduction of the configurations have added a lot of other files (starting with `zig-cache/h/`). If no one but me uses vscode, I can add them to the .gitignore file if you wish.

### CODE REVIEW

**Comment by dvmason** [comment]
Thanks. The vscode stuff seems useful, but all the generated files should go into .gitignore. Also I've made a lot of changes to zig/fibonacci.zig, so it would be a lot cleaner to merge from dvmason:main first.

**Review by dvmason — APPROVED** [review]
Looks good

**Review by dvmason — APPROVED** [review]
Looks good

**Review by dvmason — CHANGES_REQUESTED** [review]
zig-cache needs to go into .gitignore

**Comment by JanBaig** [comment]
For commit [848e621](https://github.com/dvmason/Zag-Smalltalk/pull/9/commits/848e621caa5dce85d86f015c35a4e7e8c0ddcb85)
I just noticed - I accidentally rejected the new changes from `zobject.zig` when trying to merge 
Not too familiar with reverting merges and re-doing the processes, but I should have it figured out soon  and will update here

**Comment by JanBaig** [comment]
> For commit [848e621](https://github.com/dvmason/Zag-Smalltalk/pull/9/commits/848e621caa5dce85d86f015c35a4e7e8c0ddcb85) I just noticed - I accidentally rejected the new changes from `zobject.zig` when trying to merge Not too familiar with reverting merges and re-doing the processes, but I should have it figured out soon and will update here

Reverted changes - all good now!

**Pull request merged**
